application:
  port: 8000
  host: 0.0.0.0
  build_path: "/home/ethan/repo/thai-shop/backend/build"
  item_path: "/home/ethan/repo/thai-shop/items"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "db"
  require_ssl: false
