application:
  port: 8000
  host: 0.0.0.0
  build_path: "/home/ethan/repo/thai-shop/frontend/build"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "db"
  require_ssl: false
